title: "論理演算可能な正規表現エンジンを作ろう"
summary: "正規表現で、否定や論理積が出来たらいいなと思ったことはありませんか？
正規表現は文字列を評価・操作するために使われますが、文字列集合の定義とも捉えることが出来ます。
正規表現が論理演算可能なら、文字列集合の演算が可能となり、デッドコードの検出や型定義への利用など、もっと堅牢なプログラミングが可能となるでしょう。
しかし、論理演算可能な正規表現エンジンは一般的ではありません。そのため、正規表現は論理演算ができないと思っていませんか？
論理演算可能な正規表現エンジンは実装可能です。
本書は、論理演算可能な正規表現エンジンの実装と、動作サンプルを示します。"
topics: ["正規表現"]
published: true
price: 0
chapters:
  - introduction
  - policy
  - token
  - chex
  - spex
  - parser
  - builder
  - usage_dfa
  - usage_calc
  - conclusion
